const boutiqueData = {
    id: "181220271",
    lesClients: ["client1", "client2"],
    alaune: ["alaune1", "alaune2"],
    proprietaire: "PESSE",
    annee: 2024,
    long: 1.2236008,
    lePersonnel: ["user1", "user2"],
    top: false,
    isPromoted: false,
    desc: "Nous sommes une boutique en ligne à Lomé. Nous vous offrons de meilleures sous vêtements hommes et femmes 😍.",
    lesServices: ["lavage", "nettoyage"],
    likes: 0,
    gererSAV: true,
    idpartner: "laalapasca",
    adresse: "",
    balance: 0,
    nbrConsultes: 2,
    cover: "https://firebasestorage.googleapis.com/v0/b/la-a-la.appspot.com/o/coverLaaLaBoutique%2F2024-12-18%2022%3A28%3A16.228344JPEG_20241218_222815_4919603810091313996.jpg?alt=media&token=e7247519-d609-4a55-a5d2-ede60bf9e76d",
    horaires: [
      { jour: "Lundi", start: 0, end: 0 },
      { jour: "Mardi", end: 0, start: 0 },
      { jour: "Mercredi", start: 0, end: 0 },
      { jour: "Jeudi", start: 0, end: 0 },
      { jour: "Vendredi", start: 0, end: 0 },
      { jour: "Samedi", start: 0, end: 0 },
      { jour: "Dimanche", start: 0, end: 0 }
    ],
    isLoyerPaid: true,
    lesCategories: ["cat1", "cat2"],
    nbrArticle: 0,
    isdelete: false,
    etoile: 0,
    lesConsultes: ["consult1", "consult2"],
    likees: [],
    type: "Boutique",
    iscert: false,
    isdesactive: false,
    idCompte: "",
    isboosted: false,
    date: "18-12-2024",
    lesArticles: ["article1", "article2"],
    duree: 30,
    nom: "Flo lingerie"
  };

 export { boutiqueData };;