// const boutiqueData = {
//     id: "181220271",
//     lesClients: ["client1", "client2"],
//     alaune: ["alaune1", "alaune2"],
//     proprietaire: "PESSE",
//     annee: 2024,
//     long: 1.2236008,
//     lePersonnel: ["user1", "user2"],
//     top: false,
//     isPromoted: false,
//     desc: "Nous sommes une boutique en ligne à Lomé. Nous vous offrons de meilleures sous vêtements hommes et femmes 😍.",
//     lesServices: ["lavage", "nettoyage"],
//     likes: 0,
//     gererSAV: true,
//     idpartner: "laalapasca",
//     adresse: "",
//     balance: 0,
//     nbrConsultes: 2,
//     cover: "https://firebasestorage.googleapis.com/v0/b/la-a-la.appspot.com/o/coverLaaLaBoutique%2F2024-12-18%2022%3A28%3A16.228344JPEG_20241218_222815_4919603810091313996.jpg?alt=media&token=e7247519-d609-4a55-a5d2-ede60bf9e76d",
//     horaires: [
//       { jour: "Lundi", start: 8, start_min: 25, end: 17, end_min: 30 },
//       { jour: "Mardi", start: 8, start_min: 25, end: 17, end_min: 30},
//       { jour: "Mercredi", start: 8, start_min: 25, end: 17, end_min: 30},
//       { jour: "Jeudi", start: 8, start_min: 25, end: 17, end_min: 30},
//       { jour: "Vendredi", start: 8, start_min: 25, end: 17, end_min: 30},
//       { jour: "Samedi", start: 8, start_min: 25, end: 12, end_min: 30},
//       { jour: "Dimanche", start: 8, start_min: 25, end: 12, end_min: 30}
//     ],
//     isLoyerPaid: true,
//     lesCategories: ["cat1", "cat2"],
//     nbrArticle: 0,
//     isdelete: false,
//     etoile: 0,
//     lesConsultes: ["consult1", "consult2"],
//     likees: [],
//     type: "Boutique",
//     iscert: false,
//     isdesactive: false,
//     idCompte: "",
//     isboosted: false,
//     date: "18-12-2024",
//     lesArticles: ["article1", "article2"],
//     duree: 30,
//     nom: "Flo lingerie"
//   };

//  export default boutiqueData ;


const boutiqueData = {
  id: "181220271",
  lesClients: [
    { id: "client1", nom: "Alice Dupont", email: "alice.dupont@example.com", tel: "+123456789" },
    { id: "client2", nom: "Bob Martin", email: "bob.martin@example.com", tel: "+987654321" },
    { id: "client3", nom: "Charlie Brown", email: "charlie.brown@example.com", tel: "+1122334455" },
  ],
  alaune: [
    { id: "alaune1", nom: "Soutien-gorge dentelle", prix: 29.99, image: "https://example.com/alaune1.jpg" },
    { id: "alaune2", nom: "Boxer homme coton", prix: 19.99, image: "https://example.com/alaune2.jpg" },
  ],
  proprietaire: "PESSE",
  annee: 2024,
  long: 1.2236008,
  lePersonnel: [
    { id: "user1", nom: "Emma Watson", role: "Gérante" },
    { id: "user2", nom: "John Doe", role: "Vendeur" },
  ],
  top: false,
  isPromoted: false,
  desc: "Nous sommes une boutique en ligne à Lomé. Nous vous offrons de meilleures sous-vêtements pour hommes et femmes 😍. Découvrez notre collection exclusive et profitez d'un confort inégalé.",
  lesServices: [
    { id: "lavage", nom: "Lavage professionnel", description: "Service de lavage et repassage pour vos sous-vêtements." },
    { id: "nettoyage", nom: "Nettoyage à sec", description: "Nettoyage délicat pour préserver la qualité de vos vêtements." },
  ],
  likes: 0,
  gererSAV: true,
  idpartner: "laalapasca",
  adresse: "123 Rue de la Mode, Lomé, Togo",
  balance: 0,
  nbrConsultes: 2,
  cover: "https://firebasestorage.googleapis.com/v0/b/la-a-la.appspot.com/o/coverLaaLaBoutique%2F2024-12-18%2022%3A28%3A16.228344JPEG_20241218_222815_4919603810091313996.jpg?alt=media&token=e7247519-d609-4a55-a5d2-ede60bf9e76d",
  horaires: [
    { jour: "Lundi", start: 8, start_min: 25, end: 17, end_min: 30 },
    { jour: "Mardi", start: 8, start_min: 25, end: 17, end_min: 30 },
    { jour: "Mercredi", start: 8, start_min: 25, end: 17, end_min: 30 },
    { jour: "Jeudi", start: 8, start_min: 25, end: 17, end_min: 30 },
    { jour: "Vendredi", start: 8, start_min: 25, end: 17, end_min: 30 },
    { jour: "Samedi", start: 8, start_min: 25, end: 12, end_min: 30 },
    { jour: "Dimanche", start: 8, start_min: 25, end: 12, end_min: 30 },
  ],
  isLoyerPaid: true,
  lesCategories: [
    { id: "cat1", nom: "Sous-vêtements femmes", description: "Collection de lingerie pour femmes." },
    { id: "cat2", nom: "Sous-vêtements hommes", description: "Collection de boxers et caleçons pour hommes." },
  ],
  nbrArticle: 0,
  isdelete: false,
  etoile: 0,
  lesConsultes: [
    { id: "consult1", nom: "Jean Dupont", email: "jean.dupont@example.com" },
    { id: "consult2", nom: "Marie Curie", email: "marie.curie@example.com" },
  ],
  likees: [],
  type: "Boutique",
  iscert: false,
  isdesactive: false,
  idCompte: "",
  isboosted: false,
  date: "18-12-2024",
  lesArticles: [
    {
      id: "article1",
      nom: "Soutien-gorge dentelle noire",
      prix: 29.99,
      description: "Soutien-gorge en dentelle noire, confortable et élégant.",
      image: "https://images.undiz.com/on/demandware.static/-/Sites-ZLIN-master/default/dw2894eca7/654736605_6.jpg?sw=550&sh=655",
      categorie: "cat1",
    },
    {
      id: "article2",
      nom: "Boxer homme coton gris",
      prix: 19.99,
      description: "Boxer en coton gris, doux et respirant.",
      image: "https://vondutch.fr/16196-superlarge_default/Lot-de-5-boxers-homme-Original.jpg",
      categorie: "cat2",
    },
  ],
  duree: 30,
  nom: "Flo lingerie",
};

export default boutiqueData;